//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public int Id_Nhom { get; set; }
        public int Id_MH { get; set; }
        public Nullable<bool> CoQuyen { get; set; }
    
        public virtual ManHinh ManHinh { get; set; }
        public virtual NhomNhanVien NhomNhanVien { get; set; }
    }
}
